<?php
require_once "NotLogin.php";
require_once "Header.php";
echo "<h4>开发目的</h4>";
CreateText("在");
CreateLink("https://xiaoheiban.cn", "晓黑板");
CreateText("下线后作为替代品");
echo "<br />";
echo "<h4>编程语言</h4>";
CreateText("后端使用PHP，数据库使用MySQL，前端使用HTML、CSS和少数的JS");
echo "<br />";
echo "<h4>开发者＆站长</h4>";
CreateText("老陈，曾经开发过微信小程序“聊天加密”，精通PHP和C++，熟练掌握VBS");
echo "<br />";
echo "<h4>开源情况</h4>";
CreateText("其中用到了开源代码");
CreateLink("https://github.com/PHPOffice/PHPExcel", "PHPExcel");
CreateText("（用来创建xlsx表格）和");
CreateLink("https://github.com/PHPMailer/PHPMailer", "PHPMailer");
CreateText("（用来使用SMTP发送电子邮件）");
echo "<br />";
CreateText("本项目已在");
CreateLink("https://github.com/langningchen/ClassWeb", "此处Github上");
CreateText("开源，欢迎大家Watch, Star, Fork, Issue, PR");
echo "<br />";
echo "<h4>联系我</h4>";
CreateLink("mailto:langningc2009.ml@outlook.com", "站长邮箱");
echo "<br />";
echo "<h4>使用的服务</h4>";
CreateText("服务器：");
CreateLink("https://www.infinityfree.net", "Infinity free");
echo "<br />";
CreateText("域名：");
CreateLink("https://www.freenom.com/", "Freenom");
echo "<br />";
CreateText("邮件：");
CreateLink("https://www.outlook.com/", "Outlook");
require_once "Footer.php";
